### PR TITLE
Option for off setting height of wrapper

### PR DESCRIPTION
**Pull request by landsman**
Hi,
is possible add new option to "on/off" this row: https://github.com/imakewebthings/waypoints/blob/master/src/shortcuts/sticky.js#L26 please?

I don't want adding wrong height to wrapper :-( It makes me problems.

Thank you!

### CODE REVIEW

**Comment by landsman** [comment]
Here is a video of my problem: https://www.youtube.com/watch?v=RIjO-tw4z2A&feature=youtu.be

**Comment by landsman** [comment]
What do you say? :)

**Comment by stephan-v** [comment]
Project seems dead.

**Comment by landsman** [comment]
yeah :-(

**Comment by imakewebthings** [comment]
Pictured: me not feeling the shame you're trying to impose for prioritizing other things at the moment. 

img_2694

**Comment by stephan-v** [comment]
Thanks for showing how little you care, at least we know not to use this any more and we can move on to build something better.

**Comment by landsman** [comment]
@imakewebthings I understand. Make a happy family and don't think about unimportant thing (for now) ... just some temporary maintainer could be good, what you think?

**Comment by fommil** [comment]
I am so doing this image thing next time I get a privileged user demand my time. You captured my entire blog post, and more, in one image https://medium.com/@fommil/the-open-source-entitlement-complex-bcb718e2326d :heart:

**Pull request closed without merging**
