### PR TITLE
Pass items to onAfterPageLoad

### PR DESCRIPTION
**Pull request by CHH**
When using masonry or isotope it's necessary to know the items which have to be relayouted. This change passes the items that were extracted of the response to the `onAfterPageLoad` callback. Using that, efficient relayouting can be accomplished by using isotope's `appended` method with the passed items.

### CODE REVIEW

**Comment by imakewebthings** [comment]
:+1: I'm down for adding this. Would you be able to add/amend tests for this?

**Comment by CHH** [comment]
@imakewebthings I'm not really into JS build and testing tools, I would need some time figuring this out. Not sure.

**Comment by imakewebthings** [comment]
@CHH That's ok, figured I'd ask. I can add them myself between when I merge and release. No estimate on when that will be though.

**Comment by CHH** [comment]
@imakewebthings I made a simplistic test case for the feature, would you mind having a look?

**Comment by tomashalo** [comment]
Hello, can you write the example how to implement waypoints infinite scroll with Isotope the right way? Thank you for your time!

**Comment by CHH** [comment]
@tomashalo here you go:

```js
// Init Isotope
$i = $(".my-item-container").isotope({
  itemSelector: '.item',
  layoutMode: 'masonry',
  masonry: {
    columnWidth: 252,
    isFitWidth: true
  }
})

new Waypoint.Infinite({
  element: $(".my-item-container")[0],
  more: ".my-pagination > .next > a",
  items: ".my-item-container > .item",
  onAfterPageLoad: function ($items) {
    $i.imagesLoaded(function () {
      $i.isotope("appended", $items)
    })
  }
})
```

You should also make sure that the inserted items have a default styling of `opacity: 0; transform: scale(0.001);` so Isotope's animations look correctly on insert.

**Comment by tomashalo** [comment]
Thanks CHH, but one more thing:
How can i call  <code>$container.isotope('layout');</code> inside <code>onAfterPageLoad</code> function? I tried <code>$i.isotope('layout');</code> but with no success. I need it  for the correct positioning of rendered elements with percentage width. Thank you.

**Comment by CHH** [comment]
@tomashalo I don't have so much experience using Isotope, but I thought `isotope("appended")` should take care of this?

**Pull request merged**
