### PR TITLE
Add commonjs support

### PR DESCRIPTION
**Pull request by keoghpe**
This commit is nothing fancy but adds commonjs support out of the box. It's currently just a hack that allows immediate use with Browserify. There are much better ways to do this but this provides immediate use. I know that support was being [discussed last year](https://github.com/imakewebthings/waypoints/issues/262), but there doesn't appear to be any support [currently](https://github.com/imakewebthings/waypoints/issues/421).

### CODE REVIEW

**Comment by imakewebthings** [comment]
These lib files are built from src by gulp.

I just closed two issues saying I wasn't going to support CommonJS. I didn't think about adding yet-another-build. I could be convinced if you're willing to get this working using the existing src and adding something to the gulp pipeline.

**Comment by kentmw** [comment]
+1 being able to use this library with Browserify is a must! at least in my opinion

**Comment by jarodtaylor** [comment]
I can finally use waypoints. Thanks for this shim @keoghpe! Kinda silly that we can't use this right out of the box.

**Comment by asalisbury** [comment]
Yes, I don't understand why this isn't the single highest priority. In late 2015, I don't understand how one can expect a JS library, plugin, whatever to persist into the future without UMD or at least commonjs support. So many people today are using Webpack, Browserify, etc. If I magically am afforded some time in the near future, I would be happy to try to help make this happen.

**Comment by imakewebthings** [comment]
Closing this for the reason stated in my first comment. Please see https://github.com/imakewebthings/waypoints/issues/458#issuecomment-151735949 for more info.

**Pull request closed without merging**
