### PR TITLE
Prevents console warnings from disabled waypoints

### LINKED ISSUE #364: Debug script should not throw Errors if waypoint is disabled
What it says on the tin. Brought up through https://github.com/trek/ember-api/issues/11.

### PR DESCRIPTION
**Pull request by lsthornt**
In reference to trek/ember-api#11. Resolves #364.

### CODE REVIEW

**Comment by lsthornt** [comment]
Tests are passing locally, so I'm unsure about the 50 failures on Travis. Rebuild?

**Comment by imakewebthings** [comment]
Perfect, thanks.

The Travis thing is throwing me for a loop. Tests also work for me locally. I suspect there is a timing issue that only presents on the slower Travis boxes, but so far I can't identify anything that would break the Inview tests outside of Jasmine (or at least the version I'm using) botching the order of things. If you happen to see anything, let me know. I'm working to simplify and speed up the tests in general + upgrade to using Jasmine 2.

**Comment by lsthornt** [comment]
Thanks, Caleb! In reference to the ember-api issue, how could I go about getting a new version published to bower?

Also, I'm not sure how `debug.js` would be accounted for by semver. Feels like it should be exempt, so this could just warrant `3.0.2`?

**Comment by imakewebthings** [comment]
For bower I need to git tag the new version. Bower should pick up the tag automatically.

I have API additions that I merged into master before this fix came along, so I'm going to bump to 3.1.0. I'm still learning/putting-into-practice the finer points of semver, such as in times like this putting all bug fixes into a patch version bump, then separating the API additions out to be the only changes in the minor bump. Next time. For now, this will all go into 3.1.0. I'll post here again when the tag is pushed.

**Comment by imakewebthings** [comment]
@lsthornt `3.1.0` cut. Happy coding.

**Comment by lsthornt** [comment]
:+1: :confetti_ball: thanks man

**Pull request merged**
